apiVersion: core.oam.dev/v1beta1
kind: Application 
metadata:
  name: sih-application
  annotations:
    version: 0.10.1
    description: "This is full SIH stack"
spec:
  components:
    - name: bart-sr-model
      type: webservice
      properties:
        image: dhairyagupta/petition-success:latest
        cpu: "1"
        memory: 3Gi
        ports:
            - port: 8080
              expose: true
      traits: 
        - type: napptive-ingress
          properties:
            name: bart-sr-model-ingress
            port: 8080
            path: /
