apiVersion: core.oam.dev/v1beta1
kind: Application 
metadata:
  name: sih-backend
  annotations:
    version: 0.10.1
    description: "This is full SIH stack"
spec:
  components:
    - name: backend
      type: webservice
      properties:
        image: nimish8/backend
        cpu: "512m"
        memory: 2Gi
        ports:  
          - port: 8000
            expose: true
      traits:
        - type: napptive-ingress
          properties:
            name: backend-ingress
            port: 8000
            path: /api
